version: 0.0.1-{build}-{branch}

shallow_clone: true

environment:
  matrix:
  - LUA: "lua 5.1"
  - LUA: "lua 5.2"
  - LUA: "lua 5.3"
  - LUA: "luajit 2.1"

configuration:
  - mingw
  - vs_32
  - vs_64

install:
  - set PATH=%CD%\env\bin;C:\Python27\Scripts;C:\MinGW\bin;%PATH%
  - pip install hererocks
  - hererocks env --%LUA% --target %configuration% --luarocks latest

build: Script

build_script:
- lua -v
- luarocks --version

after_build:
- lua -e "print(require('queue') == nil)"

before_test:
- luarocks install busted
- luarocks install luacov
- luarocks install luacov-multiple

test_script:
- echo "Starting unit tests:"
- lua -lluacov test.lua

after_test:
- luarocks make queue-0.0.1-0.rockspec